# Point to CircuitPython, not MicroPython
MPY_DIR = /home/chmod775/repos/bittino-pi-cpy

MOD = dyn_example_basic
SRC = dyn_example_basic.c
ARCH = armv6m
CFLAGS += -Wno-unused-variable

include $(MPY_DIR)/py/dynruntime.mk