# Point to CircuitPython, not MicroPython
MPY_DIR = /home/chmod775/repos/bittino-pi-cpy

MOD = trumpet_math
SRC = trumpet_math.c
ARCH = armv6m
CFLAGS += -Wno-unused-variable

include $(MPY_DIR)/py/dynruntime.mk